2023-09-17 19:10:38,289:ERROR:error:'MainApp' object has no attribute 'threadPool'
Traceback (most recent call last):
  File "logo_flash_main.py", line 933, in closeEvent
    self.threadPool.clear()
AttributeError: 'MainApp' object has no attribute 'threadPool'
